### ISSUE TITLE
Rename variables to keep consistency with DHS

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/MICS6#1]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/XWeng/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/XWeng/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>
Suggested by Sven, the variables listed below should be renamed to be consistent with DHS template. The variables listed on the left should be renamed to the right hand side. 

- [x] Kindly note that currently the modifications will only be applied to MICS6. 
- [x] Potentially same changes should be made to previous waves, MICS5, MICS4, etc.

<body link="#0563C1" vlink="#954F72">

MICS   (different var name) | MICS_vars
-- | --
c_del_eff1 | c_sba_eff1
c_del_eff1_q | c_sba_eff1_q
c_del_eff2 | c_sba_eff2
c_del_eff2_q | c_sba_eff2_q
w_unmet | w_unmet_fp
c_measles_vacc | c_measles
c_mateduc | w_mateduc
ind_sampleweight | w_sampleweight
mor_wdob | hm_dob
mor_doi | hm_doi

</body>

</html>

**Comment by wengxyu1030** [comment]
Dear @robin-wang and @wswz115 , please based on this list, rename the variables accordingly.

**Comment by jianingwwww** [comment]
Dear @wengxyu1030 and @wswz115 , I have renamed these indicators and added codes in the pull request of Belarus2019 #21

**Comment by wengxyu1030** [comment]
Thanks @jianingwwww , I have reviewed the rename code for pull request #21 , it's correct and clear. I will merge it to the main branch once the other edit request is completed in the pull request. 

Regards, 
Aline

**Comment by wengxyu1030** [comment]
The issue is now solved in the updated template. To be discussed on when to expand to earlier rounds of surveys.

**Comment by robin-wang** [comment]
Confirm and close.
