### ISSUE TITLE
Add new indicators to the current template

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/MICS6#2]
Suggested by Sven that the following indicators should also be generated from the template: c_wfa, c_hfa (previously in DHS as hc70 and hc71), and c_wfh (new).

- [x] Currently only apply this to MICS6 new surveys applied to Data Whale team. 
- [x] But later should check if the code apply to other World Bank coded survey for MICS6. (the code for these variables are expected to be standard considering the comparative standard data collection for these information)
- [x] Lastly to add the code to all previous waves. 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/XWeng/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/XWeng/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

Child   anthropometrics | c_wfa | Newly added variable for MICS | hm | Weight-for-age z-score from   survey (original variable)
-- | -- | -- | -- | --
Child anthropometrics | c_hfa | Newly added variable for MICS | hm | Height-for-age z-score from survey (original variable)
Child anthropometrics | c_wfh | Newly added variable for MICS and DHS | hm | Weight-for-hight z-score from survey (original variable)

</body>

</html>

**Comment by wengxyu1030** [comment]
Dear @robin-wang and @wswz115 , please work on this for the assigned new surveys.

**Comment by wengxyu1030** [comment]
Sven pointed out there are other indicators that would be nice to incorporate, @robin-wang has been documenting but actions await.

**Comment by robin-wang** [comment]
Status update:
- Implemented in MICS6
- Earlier wave edits will be rolled out. Issue closed.
