### ISSUE TITLE
About the sample weight

### ISSUE THREAD

**Issue by wengxyu1030** [wengxyu1030/MICS6#56]
Thanks to Ke @Ortsang 's careful work, there're mismatches of sample weights and indicators, which resulted in cases where the sample weight are missing for a lot of indicators with values. Ke and @robin-wang kindly fixed up the template accordingly.

@wengxyu1030 is looking at this systematically and will talk with the Task Team Leader on this. I will keep everyone posted if there's any update.

**Comment by robin-wang** [comment]
Thanks Aline! 
Ke and I have prioritised working on top of the variable structure that we have, and ensure the missing indicators can be checked above all. It would be great to have your insights in the application of weights in the MICS surveys for further updates. Much appreciated!

**Comment by wengxyu1030** [comment]
Dear All @robin-wang and @Ortsang ,

I have updated the template accordingly in the commit b5ca69e4a182244a5e6d2ddcc5735ff98bc55ce3

There should be no futher issue on the missing sample weight.

**Comment by robin-wang** [comment]
Sample weight updated, implemented, discussed, and confirmed with Sven.
Might need to apply this retrospectively to other waves of MICS? @wengxyu1030 I am adding a to-do just in case we forgot.
